using System;
using System.Collections.Generic;
using System.Data;
using System.Text;

namespace DataHub.Models {
    public class TimeHistDetail {
        public string RecordID { get; set; }
        public string Client { get; set; }
        public string GroupCode { get; set; }
        public string SSN { get; set; }
        public string PayrollPeriodEndDate { get; set; }
        public string MasterPayrollDate { get; set; }
        public string SiteNo { get; set; }
        public string DeptNo { get; set; }
        public string JobID { get; set; }
        public string TransDate { get; set; }
        public string EmpStatus { get; set; }
        public string BillRate { get; set; }
        public string BillOTRate { get; set; }
        public string BillOTRateOverride { get; set; }
        public string PayRate { get; set; }
        public string ShiftNo { get; set; }
        public string InDay { get; set; }
        public string InTime { get; set; }
        public string OutDay { get; set; }
        public string OutTime { get; set; }
        public string Hours { get; set; }
        public string Dollars { get; set; }
        public string ClockAdjustmentNo { get; set; }
        public string AdjustmentCode { get; set; }
        public string AdjustmentName { get; set; }
        public string TransType { get; set; }
        public string Changed_DeptNo { get; set; }
        public string Changed_InPunch { get; set; }
        public string Changed_OutPunch { get; set; }
        public string AgencyNo { get; set; }
        public string InSrc { get; set; }
        public string OutSrc { get; set; }
        public string DaylightSavTime { get; set; }
        public string Holiday { get; set; }
        public string RegHours { get; set; }
        public string OT_Hours { get; set; }
        public string DT_Hours { get; set; }
        public string RegDollars { get; set; }
        public string OT_Dollars { get; set; }
        public string DT_Dollars { get; set; }
        public string RegBillingDollars { get; set; }
        public string OTBillingDollars { get; set; }
        public string DTBillingDollars { get; set; }
        public string CountAsOT { get; set; }
        public string RegDollars4 { get; set; }
        public string OT_Dollars4 { get; set; }
        public string DT_Dollars4 { get; set; }
        public string RegBillingDollars4 { get; set; }
        public string OTBillingDollars4 { get; set; }
        public string DTBillingDollars4 { get; set; }
        public string xAdjHours { get; set; }
        public string AprvlStatus { get; set; }
        public string AprvlStatus_UserID { get; set; }
        public string AprvlStatus_Date { get; set; }
        public string AprvlAdjOrigRecID { get; set; }
        public string HandledByImporter { get; set; }
        public string AprvlAdjOrigClkAdjNo { get; set; }
        public string ClkTransNo { get; set; }
        public string ShiftDiffClass { get; set; }
        public string AllocatedRegHours { get; set; }
        public string AllocatedOT_Hours { get; set; }
        public string AllocatedDT_Hours { get; set; }
        public string Borrowed { get; set; }
        public string UserCode { get; set; }
        public string DivisionID { get; set; }
        public string CostID { get; set; }
        public string ShiftDiffAmt { get; set; }
        public string OutUserCode { get; set; }
        public string ActualInTime { get; set; }
        public string ActualOutTime { get; set; }
        public string InSiteNo { get; set; }
        public string OutSiteNo { get; set; }
        public string InVerified { get; set; }
        public string OutVerified { get; set; }
        public string InClass { get; set; }
        public string OutClass { get; set; }
        public string InTimestamp { get; set; }
        public string outTimestamp { get; set; }
        public string CrossoverStatus { get; set; }
        public string CrossoverOtherGroup { get; set; }
        public string InRoundOFF { get; set; }
        public string OutRoundOFF { get; set; }
        public string AprvlStatus_Mobile { get; set; }
        //public Int64? RecordID { get; set; }
        //public string Client { get; set; }
        //public Int32? GroupCode { get; set; }
        //public Int32? SSN { get; set; }
        //public string PayrollPeriodEndDate { get; set; }
        //public string MasterPayrollDate { get; set; }
        //public Int32? SiteNo { get; set; }
        //public Int32? DeptNo { get; set; }
        //public Int64? JobID { get; set; }
        //public string TransDate { get; set; }
        //public Int32? EmpStatus { get; set; }
        //public Decimal? BillRate { get; set; }
        //public Decimal? BillOTRate { get; set; }
        //public Decimal? BillOTRateOverride { get; set; }
        //public Decimal? PayRate { get; set; }
        //public Int32? ShiftNo { get; set; }
        //public Int32? InDay { get; set; }
        //public string InTime { get; set; }
        //public Int32? OutDay { get; set; }
        //public string OutTime { get; set; }
        //public Decimal? Hours { get; set; }
        //public Decimal? Dollars { get; set; }
        //public string ClockAdjustmentNo { get; set; }
        //public string AdjustmentCode { get; set; }
        //public string AdjustmentName { get; set; }
        //public Int32? TransType { get; set; }
        //public string Changed_DeptNo { get; set; }
        //public string Changed_InPunch { get; set; }
        //public string Changed_OutPunch { get; set; }
        //public Int32? AgencyNo { get; set; }
        //public string InSrc { get; set; }
        //public string OutSrc { get; set; }
        //public string DaylightSavTime { get; set; }
        //public string Holiday { get; set; }
        //public Decimal? RegHours { get; set; }
        //public Decimal? OT_Hours { get; set; }
        //public Decimal? DT_Hours { get; set; }
        //public Decimal? RegDollars { get; set; }
        //public Decimal? OT_Dollars { get; set; }
        //public Decimal? DT_Dollars { get; set; }
        //public Decimal? RegBillingDollars { get; set; }
        //public Decimal? OTBillingDollars { get; set; }
        //public Decimal? DTBillingDollars { get; set; }
        //public string CountAsOT { get; set; }
        //public Decimal? RegDollars4 { get; set; }
        //public Decimal? OT_Dollars4 { get; set; }
        //public Decimal? DT_Dollars4 { get; set; }
        //public Decimal? RegBillingDollars4 { get; set; }
        //public Decimal? OTBillingDollars4 { get; set; }
        //public Decimal? DTBillingDollars4 { get; set; }
        //public Decimal? xAdjHours { get; set; }
        //public string AprvlStatus { get; set; }
        //public Int32? AprvlStatus_UserID { get; set; }
        //public string AprvlStatus_Date { get; set; }
        //public Int64? AprvlAdjOrigRecID { get; set; }
        //public string HandledByImporter { get; set; }
        //public string AprvlAdjOrigClkAdjNo { get; set; }
        //public Int64? ClkTransNo { get; set; }
        //public string ShiftDiffClass { get; set; }
        //public Decimal? AllocatedRegHours { get; set; }
        //public Decimal? AllocatedOT_Hours { get; set; }
        //public Decimal? AllocatedDT_Hours { get; set; }
        //public string Borrowed { get; set; }
        //public string UserCode { get; set; }
        //public Int64? DivisionID { get; set; }
        //public string CostID { get; set; }
        //public Decimal? ShiftDiffAmt { get; set; }
        //public string OutUserCode { get; set; }
        //public string ActualInTime { get; set; }
        //public string ActualOutTime { get; set; }
        //public Int32? InSiteNo { get; set; }
        //public Int32? OutSiteNo { get; set; }
        //public string InVerified { get; set; }
        //public string OutVerified { get; set; }
        //public string InClass { get; set; }
        //public string OutClass { get; set; }
        //public Int64? InTimestamp { get; set; }
        //public Int64? outTimestamp { get; set; }
        //public string CrossoverStatus { get; set; }
        //public Int32? CrossoverOtherGroup { get; set; }
        //public string InRoundOFF { get; set; }
        //public string OutRoundOFF { get; set; }
        //public Boolean? AprvlStatus_Mobile { get; set; }
    }

}
