Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\Reports.rpt_GetTimecardUdfs_Approver.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\REPORTS.RPT_GETTIMECARDUDFS_APPROVER.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\Reports.rpt_GetTimecardUdfs_Approver.sql
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\REPORTS.RPT_GETTIMECARDUDFS_APPROVER.SQL
   86:  GO
*****

