Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\Reports.rpt_GetTimecardApprovers_Approver.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\REPORTS.RPT_GETTIMECARDAPPROVERS_APPROVER.SQL
FC: no differences encountered

