Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\Reports.rpt_GetTimecardHeader_Approver.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\REPORTS.RPT_GETTIMECARDHEADER_APPROVER.SQL
FC: no differences encountered

