Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_CECLOCK_GetMissingPunches_NEW.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_CECLOCK_GETMISSINGPUNCHES_NEW.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_CECLOCK_GetMissingPunches_NEW.sql
    1:  CREATE PROC [dbo].[usp_CECLOCK_GetMissingPunches_NEW]
    2:  (
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_CECLOCK_GETMISSINGPUNCHES_NEW.SQL
    1:  Create PROCEDURE [dbo].[usp_CECLOCK_GetMissingPunches_NEW]
    2:  (
*****

