Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_OLST_871700_SpecPay_Empl.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_OLST_871700_SPECPAY_EMPL.SQL
FC: no differences encountered

