Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_OlstUPL_GetHoursByDay2.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_OLSTUPL_GETHOURSBYDAY2.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_OlstUPL_GetHoursByDay2.sql
  101:  --
  103:  IF EXISTS
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_OLSTUPL_GETHOURSBYDAY2.SQL
  100:  --
  102:  IF EXISTS
*****

