Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_FLPI_TravelTime_EmplCalc_OT.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_FLPI_TRAVELTIME_EMPLCALC_OT.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_FLPI_TravelTime_EmplCalc_OT.sql
  101:      WHILE @@FETCH_STATUS = 0
  102:      BEGIN
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_FLPI_TRAVELTIME_EMPLCALC_OT.SQL
  100:      WHILE @@FETCH_STATUS = 0
  101:      BEGIN
*****

