Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_BRNS.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_BRNS.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_BRNS.sql
  101:    , ApprovalDate  VARCHAR(14)  --format is: YYYYMMDD HH:MM
  102:    , PayFileGroup  VARCHAR(10)
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_BRNS.SQL
  100:    , ApprovalDate  VARCHAR(14)  --format is: YYYYMMDD HH:MM
  101:    , PayFileGroup  VARCHAR(10)
*****

