Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_OlstUPL_GetHoursByDay2_bySite.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_OLSTUPL_GETHOURSBYDAY2_BYSITE.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_OlstUPL_GetHoursByDay2_bySite.sql
  101:  Create Table #tmpSSNs
  102:  ( 
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_OLSTUPL_GETHOURSBYDAY2_BYSITE.SQL
  100:  Create Table #tmpSSNs
  101:  ( 
*****

