Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_Web1_GetTHDCustomFieldValue.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_GETTHDCUSTOMFIELDVALUE.SQL
FC: no differences encountered

