Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_RDRM.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_RDRM.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_RDRM.sql
  201:  FROM #groupLastPPED tmp  
  202:  INNER JOIN TimeHistory..tblPeriodEndDates ped WITH(NOLOCK)  
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_RDRM.SQL
  200:  FROM #groupLastPPED tmp  
  201:  INNER JOIN TimeHistory..tblPeriodEndDates ped WITH(NOLOCK)  
*****

