Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_XLSImport_GAMB_Insert_THD.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_XLSIMPORT_GAMB_INSERT_THD.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_XLSImport_GAMB_Insert_THD.sql
  101:  if @DupID is NOT NULL
  102:  begin
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_XLSIMPORT_GAMB_INSERT_THD.SQL
  100:  if @DupID is NOT NULL
  101:  begin
*****

