Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPTClockDetailIndiv_T4ME.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPTCLOCKDETAILINDIV_T4ME.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPTClockDetailIndiv_T4ME.sql
  101:  #T3METempTable X
  102:  INNER JOIN
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPTCLOCKDETAILINDIV_T4ME.SQL
  100:  #T3METempTable X
  101:  INNER JOIN
*****

