Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_KronosPunchExport.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_KRONOSPUNCHEXPORT.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_KronosPunchExport.sql
  101:  o,''),0
  102:  FROM TimeHistory..tblKronosPunchExport
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_KRONOSPUNCHEXPORT.SQL
  100:  o,''),0
  101:  FROM TimeHistory..tblKronosPunchExport
*****

