Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPT_STAF_HoursRatesDollars.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPT_STAF_HOURSRATESDOLLARS.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPT_STAF_HoursRatesDollars.sql
  101:  AND tcCG.GroupCode = THD.GroupCode
  102:  LEFT JOIN TimeHistory.dbo.tblEmplNames th_EN WITH(NOLOCK)
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPT_STAF_HOURSRATESDOLLARS.SQL
  100:  AND tcCG.GroupCode = THD.GroupCode
  101:  LEFT JOIN TimeHistory.dbo.tblEmplNames th_EN WITH(NOLOCK)
*****

