Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_XLSImport_Adjustment_Insert_THD.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_XLSIMPORT_ADJUSTMENT_INSERT_THD.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_XLSImport_Adjustment_Insert_THD.sql
  101:          SELECT @UC = 'XLS'
  102:  else
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_XLSIMPORT_ADJUSTMENT_INSERT_THD.SQL
  100:          SELECT @UC = 'XLS'
  101:  else
*****

