Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_Web1_ChangeSite.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_CHANGESITE.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_Web1_ChangeSite.sql
  101:    BEGIN
  102:      -- Notes:
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_CHANGESITE.SQL
  100:    BEGIN
  101:      -- Notes:
*****

