Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_Web1_GetUndefinedReasonOnTimeCard.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_GETUNDEFINEDREASONONTIMECARD.SQL
FC: no differences encountered

