Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_DAVT_HostImport_AddTimeDetailRec.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_DAVT_HOSTIMPORT_ADDTIMEDETAILREC.SQL
FC: no differences encountered

