Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_OLST_885900_LunchRounding_SP.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_OLST_885900_LUNCHROUNDING_SP.SQL
FC: no differences encountered

