Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_CECLOCK_GetMissingPunches.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_CECLOCK_GETMISSINGPUNCHES.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_CECLOCK_GetMissingPunches.sql
    1:  CREATE PROC [dbo].[usp_CECLOCK_GetMissingPunches]
    2:  (
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_CECLOCK_GETMISSINGPUNCHES.SQL
    1:  Create PROCEDURE [dbo].[usp_CECLOCK_GetMissingPunches]
    2:  (
*****

