Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_EmplCalc_OT_Colorado.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_EMPLCALC_OT_COLORADO.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_EmplCalc_OT_Colorado.sql
  101:  DECLARE csrMultiples CURSOR FOR
  102:    SELECT RecordID FROM #tmpData GROUP BY RecordID HAVING COUNT(*) > 1
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_EMPLCALC_OT_COLORADO.SQL
  100:  DECLARE csrMultiples CURSOR FOR
  101:    SELECT RecordID FROM #tmpData GROUP BY RecordID HAVING COUNT(*) > 1
*****

