Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_PaidBreak_SP_NonWorked.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_PAIDBREAK_SP_NONWORKED.SQL
FC: no differences encountered

