Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_SplitTimeHistDetailRecord.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_SPLITTIMEHISTDETAILRECORD.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_SplitTimeHistDetailRecord.sql
  101:    BEGIN
  102:      ROLLBACK TRANSACTION;
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_SPLITTIMEHISTDETAILRECORD.SQL
  100:    BEGIN
  101:      ROLLBACK TRANSACTION;
*****

