Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_CECLOCK_InsertBreak.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_CECLOCK_INSERTBREAK.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_CECLOCK_InsertBreak.sql
  101:  @OutDay = OutDay,
  102:  @AgencyNo = AgencyNo,
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_CECLOCK_INSERTBREAK.SQL
  100:  @OutDay = OutDay,
  101:  @AgencyNo = AgencyNo,
*****

