Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_UpdatePunchDetail4.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_UPDATEPUNCHDETAIL4.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_UpdatePunchDetail4.sql
  101:          SELECT @InDay = 10 
  102:          SELECT @InTime = '12/30/1899 00:00:00'
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_UPDATEPUNCHDETAIL4.SQL
  100:          SELECT @InDay = 10 
  101:          SELECT @InTime = '12/30/1899 00:00:00'
*****

