Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPT_PATE_LaborDistCustomFieldsBySite.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPT_PATE_LABORDISTCUSTOMFIELDSBYSITE.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPT_PATE_LaborDistCustomFieldsBySite.sql
  101:      Season                VARCHAR(100) 
  102:  )   
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPT_PATE_LABORDISTCUSTOMFIELDSBYSITE.SQL
  100:      Season                VARCHAR(100) 
  101:  )   
*****

