Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_Web1_GetTimeHistDetailFaxaroo.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_GETTIMEHISTDETAILFAXAROO.SQL
FC: no differences encountered

