Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_ADSU_GetHoursByDay2_bySite.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_ADSU_GETHOURSBYDAY2_BYSITE.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_ADSU_GetHoursByDay2_bySite.sql
  101:  DECLARE @RegAvailable      NUMERIC(7,2)
  102:  DECLARE @OTAvailable       NUMERIC(7,2)
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_ADSU_GETHOURSBYDAY2_BYSITE.SQL
  100:  DECLARE @RegAvailable      NUMERIC(7,2)
  101:  DECLARE @OTAvailable       NUMERIC(7,2)
*****

***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_ADSU_GetHoursByDay2_bySite.sql
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_ADSU_GETHOURSBYDAY2_BYSITE.SQL
 1687:  GO
*****

