Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_EMER_LunchRounding_SP.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_EMER_LUNCHROUNDING_SP.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_EMER_LunchRounding_SP.sql
  101:      IF @Minutes < 23 
  102:      BEGIN
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_EMER_LUNCHROUNDING_SP.SQL
  100:      IF @Minutes < 23 
  101:      BEGIN
*****

