Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_PuertoRicoOTRules.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_PUERTORICOOTRULES.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_PuertoRicoOTRules.sql
  101:  AND en.GroupCode = @GroupCode
  102:  AND en.SSN = @SSN
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_PUERTORICOOTRULES.SQL
  100:  AND en.GroupCode = @GroupCode
  101:  AND en.SSN = @SSN
*****

***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_PuertoRicoOTRules.sql
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_PUERTORICOOTRULES.SQL
 1240:  GO
*****

