Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_Standard_PEOPLENET_GetData.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_STANDARD_PEOPLENET_GETDATA.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_Standard_PEOPLENET_GetData.sql
  101:      , RecordID               INT IDENTITY
  102:  )
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_STANDARD_PEOPLENET_GETDATA.SQL
  100:      , RecordID               INT IDENTITY
  101:  )
*****

