Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_TravelTime_AddTimeDetailRec.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_TRAVELTIME_ADDTIMEDETAILREC.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_TravelTime_AddTimeDetailRec.sql
  201:    --EXEC [Scheduler].[dbo].[usp_APP_AddNotification] 4, 4, 'TravelTime', 0, 0, @Notification, ''
  203:    -- Clean up any travel dept records that were generated by the clock due to splitting
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_TRAVELTIME_ADDTIMEDETAILREC.SQL
  200:    --EXEC [Scheduler].[dbo].[usp_APP_AddNotification] 4, 4, 'TravelTime', 0, 0, @Notification, ''
  202:    -- Clean up any travel dept records that were generated by the clock due to splitting
*****

