Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_ShiftDiff_AddSplitRec.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_SHIFTDIFF_ADDSPLITREC.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_ShiftDiff_AddSplitRec.sql
  101:  Else
  102:  Begin
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_SHIFTDIFF_ADDSPLITREC.SQL
  100:  Else
  101:  Begin
*****

