Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_Web1_ApproveAssignmentTransaction.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_APPROVEASSIGNMENTTRANSACTION.SQL
FC: no differences encountered

