Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPT_PARA_TimeDetail.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPT_PARA_TIMEDETAIL.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPT_PARA_TimeDetail.sql
  101:      end
  102:    END
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPT_PARA_TIMEDETAIL.SQL
  100:      end
  101:    END
*****

