Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_CECLOCK_GetMissingPunches_TEST.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_CECLOCK_GETMISSINGPUNCHES_TEST.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_CECLOCK_GetMissingPunches_TEST.sql
    1:  CREATE PROC [dbo].[usp_CECLOCK_GetMissingPunches_TEST]
    2:  (
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_CECLOCK_GETMISSINGPUNCHES_TEST.SQL
    1:  Create PROCEDURE [dbo].[usp_CECLOCK_GetMissingPunches_TEST]
    2:  (
*****

