Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_WTE_InsertAdjustment.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WTE_INSERTADJUSTMENT.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_WTE_InsertAdjustment.sql
  101:  IF @Client in('HILT','HLT1') AND LTRIM(RTRIM(@HoursCode)) = 'FLH'
  102:  BEGIN
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WTE_INSERTADJUSTMENT.SQL
  100:  IF @Client in('HILT','HLT1') AND LTRIM(RTRIM(@HoursCode)) = 'FLH'
  101:  BEGIN
*****

