Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_PuertoRicoOTRules_Clock.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_PUERTORICOOTRULES_CLOCK.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_PuertoRicoOTRules_Clock.sql
  101:  AND en.SSN = @SSN
  103:  IF (ISNULL(@NoOT, 0) = 1)
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_PUERTORICOOTRULES_CLOCK.SQL
  100:  AND en.SSN = @SSN
  102:  IF (ISNULL(@NoOT, 0) = 1)
*****

