Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_Standard_PEOPLENET_Clock_NEW.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_STANDARD_PEOPLENET_CLOCK_NEW.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_Standard_PEOPLENET_Clock_NEW.sql
  101:    , PayFileGroup  VARCHAR(10)
  102:    , PayBillCode   VARCHAR(10)
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_STANDARD_PEOPLENET_CLOCK_NEW.SQL
  100:    , PayFileGroup  VARCHAR(10)
  101:    , PayBillCode   VARCHAR(10)
*****

