Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_DAVT_MonthlyACT_Extract.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_DAVT_MONTHLYACT_EXTRACT.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_DAVT_MonthlyACT_Extract.sql
  101:        SET @ShiftSegmentID = @ShiftSegment
  103:        OPEN cTHD1
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_DAVT_MONTHLYACT_EXTRACT.SQL
  100:        SET @ShiftSegmentID = @ShiftSegment
  102:        OPEN cTHD1
*****

