Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_Standard_AVIONTE_Clock_new.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_STANDARD_AVIONTE_CLOCK_NEW.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_Standard_AVIONTE_Clock_new.sql
  101:    , SourceTime    VARCHAR(30)
  102:    , SourceApprove VARCHAR(30)
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_STANDARD_AVIONTE_CLOCK_NEW.SQL
  100:    , SourceTime    VARCHAR(30)
  101:    , SourceApprove VARCHAR(30)
*****

