Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPT_EmployeeDailyAndCumulativeWorkedHoursSummary.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPT_EMPLOYEEDAILYANDCUMULATIVEWORKEDHOURSSUMMARY.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPT_EmployeeDailyAndCumulativeWorkedHoursSummary.sql
  101:  WHERE 
  102:  THD.TransDate = @TDates
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPT_EMPLOYEEDAILYANDCUMULATIVEWORKEDHOURSSUMMARY.SQL
  100:  WHERE 
  101:  THD.TransDate = @TDates
*****

