Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_TRAVELTIME_ProcessEthernetPunches.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_TRAVELTIME_PROCESSETHERNETPUNCHES.SQL
FC: no differences encountered

