Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_AddTimeDetailRecWithBreak.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_ADDTIMEDETAILRECWITHBREAK.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_AddTimeDetailRecWithBreak.sql
  101:  DECLARE @dtInTime DateTime
  102:  DECLARE @dtOutTime DateTime
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_ADDTIMEDETAILRECWITHBREAK.SQL
  100:  DECLARE @dtInTime DateTime
  101:  DECLARE @dtOutTime DateTime
*****

