Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_PATE_AddAdjustment.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_PATE_ADDADJUSTMENT.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_PATE_AddAdjustment.sql
  101:  AND GroupCode = @GroupCode
  102:  AND SSN = @SSN
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_PATE_ADDADJUSTMENT.SQL
  100:  AND GroupCode = @GroupCode
  101:  AND SSN = @SSN
*****

