Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_ReAllocateSalaryHours.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_REALLOCATESALARYHOURS.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_ReAllocateSalaryHours.sql
  101:    AprvlStatus_UserID   int NULL DEFAULT 0
  102:  )
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_REALLOCATESALARYHOURS.SQL
  100:    AprvlStatus_UserID   int NULL DEFAULT 0
  101:  )
*****

