Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_HCPA_SpecPay_ShiftDiff_BasedOnStartTime.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_HCPA_SPECPAY_SHIFTDIFF_BASEDONSTARTTIME.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_HCPA_SpecPay_ShiftDiff_BasedOnStartTime.sql
  101:  select 
  102:  RecordID, 
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_HCPA_SPECPAY_SHIFTDIFF_BASEDONSTARTTIME.SQL
  100:  select 
  101:  RecordID, 
*****

