Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GambroMonthlyAccrualAddRec.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GAMBROMONTHLYACCRUALADDREC.SQL
FC: no differences encountered

