Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_MPOW_PCT_NEW.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_MPOW_PCT_NEW.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_MPOW_PCT_NEW.sql
  101:          WHERE (
  102:                     (CASE WHEN DATEPART(dw, PPED) = 2 AND DATEPART(dw, @Today) = 5 THEN 1 ELSE 0 END = 1) -- EOW Monday
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_MPOW_PCT_NEW.SQL
  100:          WHERE (
  101:                     (CASE WHEN DATEPART(dw, PPED) = 2 AND DATEPART(dw, @Today) = 5 THEN 1 ELSE 0 END = 1) -- EOW Monday
*****

