Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_WEB1_ChangeShiftDiff_Post.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_CHANGESHIFTDIFF_POST.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_WEB1_ChangeShiftDiff_Post.sql
  101:  BEGIN
  102:    DECLARE @Message varchar(1024)
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_CHANGESHIFTDIFF_POST.SQL
  100:  BEGIN
  101:    DECLARE @Message varchar(1024)
*****

