Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPT_UDF_Entries.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPT_UDF_ENTRIES.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPT_UDF_Entries.sql
  101:  INSERT INTO #tmpEmpl
  102:  (
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPT_UDF_ENTRIES.SQL
  100:  INSERT INTO #tmpEmpl
  101:  (
*****

