Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_EmplCalc_OT_OTByWorkedSite.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_EMPLCALC_OT_OTBYWORKEDSITE.SQL
FC: no differences encountered

