Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_Web1_GetTimeHistDetail_RecordID.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_GETTIMEHISTDETAIL_RECORDID.SQL
FC: no differences encountered

