Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_PLite_FixPunchPost.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_PLITE_FIXPUNCHPOST.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_PLite_FixPunchPost.sql
  101:    DECLARE @tmpHours numeric(5,2)
  102:    DECLARE @tmpMinutes int
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_PLITE_FIXPUNCHPOST.SQL
  100:    DECLARE @tmpHours numeric(5,2)
  101:    DECLARE @tmpMinutes int
*****

