Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_LSA_Calc_Baylor_ALBEMARLE.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_LSA_CALC_BAYLOR_ALBEMARLE.SQL
FC: no differences encountered

