Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPTPayCodeSelection_Prod.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPTPAYCODESELECTION_PROD.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPTPayCodeSelection_Prod.sql
  101:    Set @OrigUserID = isnull(@OrigUserID,0)
  102:    IF @OrigUserID <> 0
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPTPAYCODESELECTION_PROD.SQL
  100:    Set @OrigUserID = isnull(@OrigUserID,0)
  101:    IF @OrigUserID <> 0
*****

