Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_DAVT_SpecPay_PdBreak_Dept100.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_DAVT_SPECPAY_PDBREAK_DEPT100.SQL
FC: no differences encountered

