Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_DAVT_UploadPS_GetUploadRecs_PPED_PreClose.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_DAVT_UPLOADPS_GETUPLOADRECS_PPED_PRECLOSE.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_DAVT_UploadPS_GetUploadRecs_PPED_PreClose.sql
  101:  IF @Accrual = 0
  102:  BEGIN
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_DAVT_UPLOADPS_GETUPLOADRECS_PPED_PRECLOSE.SQL
  100:  IF @Accrual = 0
  101:  BEGIN
*****

