Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_WEB1_DAVT_CheckUnpaidPTO_OLD.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_DAVT_CHECKUNPAIDPTO_OLD.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_WEB1_DAVT_CheckUnpaidPTO_OLD.sql
  101:      SSN int,
  102:      Dateadded datetime,
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_DAVT_CHECKUNPAIDPTO_OLD.SQL
  100:      SSN int,
  101:      Dateadded datetime,
*****

