Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_MPOW_PCT_LateApproval.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_MPOW_PCT_LATEAPPROVAL.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_MPOW_PCT_LateApproval.sql
  101:  CREATE TABLE #groupCPAWks  
  102:  (  
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_MPOW_PCT_LATEAPPROVAL.SQL
  100:  CREATE TABLE #groupCPAWks  
  101:  (  
*****

