Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPTPayCodeSelection.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPTPAYCODESELECTION.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPTPayCodeSelection.sql
  201:  IF @Sites <> 'ALL' and @Sites is not null
  202:  begin
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPTPAYCODESELECTION.SQL
  200:  IF @Sites <> 'ALL' and @Sites is not null
  201:  begin
*****

***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPTPayCodeSelection.sql
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPTPAYCODESELECTION.SQL
  357:  GO
*****

