Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_RandstadUpload_GetUploadRecs.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_RANDSTADUPLOAD_GETUPLOADRECS.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_RandstadUpload_GetUploadRecs.sql
  101:  */
  102:  IF (@Client = 'RAND' AND @GroupCode = 607300)
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_RANDSTADUPLOAD_GETUPLOADRECS.SQL
  100:  */
  101:  IF (@Client = 'RAND' AND @GroupCode = 607300)
*****

