Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_WGET_Text_TimeCard.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WGET_TEXT_TIMECARD.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_WGET_Text_TimeCard.sql
  101:          RETURN
  102:  END
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WGET_TEXT_TIMECARD.SQL
  100:          RETURN
  101:  END
*****

