Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_EmplCalc_TempoTimecardCache.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_EMPLCALC_TEMPOTIMECARDCACHE.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_EmplCalc_TempoTimecardCache.sql
  101:  , RH NUMERIC(5,2) NULL
  102:  , PP BIT
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_EMPLCALC_TEMPOTIMECARDCACHE.SQL
  100:  , RH NUMERIC(5,2) NULL
  101:  , PP BIT
*****

