Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_FountainView_EmplCalc_OT_SubAcutes.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_FOUNTAINVIEW_EMPLCALC_OT_SUBACUTES.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_FountainView_EmplCalc_OT_SubAcutes.sql
  101:          ELSE
  102:            SET @OT_Hours = @Hours
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_FOUNTAINVIEW_EMPLCALC_OT_SUBACUTES.SQL
  100:          ELSE
  101:            SET @OT_Hours = @Hours
*****

