Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_SNES_Clock.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_SNES_CLOCK.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_GenericPayrollUpload_GetRecs_SNES_Clock.sql
  101:    , PayAmount     NUMERIC(7,2)
  102:    , BillAmount    NUMERIC(7,2)  
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_GENERICPAYROLLUPLOAD_GETRECS_SNES_CLOCK.SQL
  100:    , PayAmount     NUMERIC(7,2)
  101:    , BillAmount    NUMERIC(7,2)  
*****

