Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_KronosPunchExport_STAF.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_KRONOSPUNCHEXPORT_STAF.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_KronosPunchExport_STAF.sql
  101:  AND thd.SSN = ed.SSN
  102:  AND thd.DeptNo = ed.Department
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_KRONOSPUNCHEXPORT_STAF.SQL
  100:  AND thd.SSN = ed.SSN
  101:  AND thd.DeptNo = ed.Department
*****

