Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_AutomatedPTO_ProcessTrans.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_AUTOMATEDPTO_PROCESSTRANS.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_AutomatedPTO_ProcessTrans.sql
  101:    IF @Client = 'GAMB' OR @Client = 'GTS'
  102:    BEGIN
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_AUTOMATEDPTO_PROCESSTRANS.SQL
  100:    IF @Client = 'GAMB' OR @Client = 'GTS'
  101:    BEGIN
*****

