Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_TandemDailyExtract_GetRecs.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_TANDEMDAILYEXTRACT_GETRECS.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_TandemDailyExtract_GetRecs.sql
  101:          END
  102:          FETCH NEXT FROM cGroups INTO @GroupCode, @PPED, @CoCode
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_TANDEMDAILYEXTRACT_GETRECS.SQL
  100:          END
  101:          FETCH NEXT FROM cGroups INTO @GroupCode, @PPED, @CoCode
*****

