Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_OlstUPL_GetHoursByDay2_bySite_PROJ_OLD.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_OLSTUPL_GETHOURSBYDAY2_BYSITE_PROJ_OLD.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_OlstUPL_GetHoursByDay2_bySite_PROJ_OLD.sql
  101:    SSN INT, 
  102:    TransCount INT, 
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_OLSTUPL_GETHOURSBYDAY2_BYSITE_PROJ_OLD.SQL
  100:    SSN INT, 
  101:    TransCount INT, 
*****

