Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_TravelTime_GetSplitTravelRecs.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_TRAVELTIME_GETSPLITTRAVELRECS.SQL
FC: no differences encountered

