Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPT_DuplicateHours.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPT_DUPLICATEHOURS.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_RPT_DuplicateHours.sql
  101:  --Print getdate()
  103:  SELECT DISTINCT
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_RPT_DUPLICATEHOURS.SQL
  100:  --Print getdate()
  102:  SELECT DISTINCT
*****

