Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_WEB1_Approval_UpdateAllEmployeesTimeCard_Clustered.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_APPROVAL_UPDATEALLEMPLOYEESTIMECARD_CLUSTERED.SQL
FC: no differences encountered

