Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_UpdatePunchDetail3.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_UPDATEPUNCHDETAIL3.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_UpdatePunchDetail3.sql
  101:    SELECT @InSrc = '9' 
  102:    SELECT @ActualInTime = NULL  
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_UPDATEPUNCHDETAIL3.SQL
  100:    SELECT @InSrc = '9' 
  101:    SELECT @ActualInTime = NULL  
*****

