Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_HCPA_SpecPay_MealPeriod_CA.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_HCPA_SPECPAY_MEALPERIOD_CA.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_HCPA_SpecPay_MealPeriod_CA.sql
  101:  -- 
  102:  Set @RecordCount = 0
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_HCPA_SPECPAY_MEALPERIOD_CA.SQL
  100:  -- 
  101:  Set @RecordCount = 0
*****

