Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_Web1_PayPeriodClose_AutoAcceptMissingPunches.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_WEB1_PAYPERIODCLOSE_AUTOACCEPTMISSINGPUNCHES.SQL
FC: no differences encountered

