Comparing files C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_DSWaters_FixSalary.sql and C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_DSWATERS_FIXSALARY.SQL
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\DB\usp_APP_DSWaters_FixSalary.sql
  101:          AND AdjustmentName = 'SALARY'
  104:        IF (@@ERROR = 0)
***** C:\PROJECTS\RECID-EXP\EXPORTED-SQLS\TFS\USP_APP_DSWATERS_FIXSALARY.SQL
  100:          AND AdjustmentName = 'SALARY'
  103:        IF (@@ERROR = 0)
*****

